# Copyright (c) 2001-2018 by SAP SE, Walldorf, Germany.
# All rights reserved. Confidential and proprietary.

# ansible 2.4
---
  - name: Setup SapMachine Master server
    hosts: SapMachineMaster
    gather_facts: False
    pre_tasks:
      - name: 'install python2'
        raw: sudo apt-get update && sudo apt-get -qq -y --no-install-recommends install python
    vars:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: SapMachine.pem
      slave_jar_version: 3.16
      jenkins_master_url: https://ci.sapmachine.io/computer/agent-linux-x86_64-1/slave-agent.jnlp
      jenkins_slave_name: agent-linux-x86_64-1

    tasks:

      - name: install apt-transport-https
        apt:
          name: apt-transport-https
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.apt-transport-https

      - name: add docker apt key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
        become: yes
        tags:
          - packages.docker_key

      - name: add docker repository
        apt_repository:
         repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
         state: present
        become: yes
        tags:
          - packages.docker_repository

      # install docker, docker-compose, OpenJDK 8 JRE
      - name: install docker-ce
        apt:
          name: docker-ce
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.docker-ce

      - name: install docker-compose
        apt:
          name: docker-compose
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.docker-compose

      - name: install OpenJDK 8 JRE
        apt:
         name: openjdk-8-jre
         state: latest
         install_recommends: no
        become: yes
        tags:
          - packages.openjdk
          - jenkins_slave

      # create sapmachine group and user
      # used for running the docker container
      - name: create sapmachine group
        group:
          name: sapmachine
          state: present
        become: yes
        tags:
          - groups.create_sapmachine

      - name: create sapmachine user
        user:
          name: sapmachine
          comment: "SapMachine user"
          group: sapmachine
          groups: sapmachine, docker
        become: yes
        tags:
          - users.create_sapmachine

      # create jenkins group and user
      # used for running the jenkins slave
      - name: create jenkins group
        group:
          name: jenkins
          state: present
        become: yes
        tags:
          - jenkins_slave
          - groups.create_jenkins

      - name: create jenkins user
        user:
          name: jenkins
          comment: "Jenkins user"
          groups: jenkins, docker
        become: yes
        tags:
          - jenkins_slave
          - users.create_jenkins

      # copy the sapmachine master files, containing the docker container
      # and docker compose configuration
      - name: copy sapmachine_master files
        synchronize:
          src: ../../
          dest: /home/sapmachine/sapmachine_master
          recursive: yes
          rsync_opts:
            - "--exclude=.git*"
            - "--exclude=ansible"
        become: yes
        become_user: sapmachine
        tags:
          - sapmachine.copy

      # set the ownership of samachine_master to sapmachine:sapmachine
      - name: set ownership of sapmachine_master
        file:
          path: /home/sapmachine/sapmachine_master
          owner: sapmachine
          group: sapmachine
          recurse: yes
        become: yes
        tags:
          - sapmachine.set_ownership

      # create the jenkins slave home directory
      - name: create Jenkins Slave home directory
        file:
          path: /home/jenkins/slave-home
          state: directory
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave
          - jenkins_slave.create_home

      # download the jenkins slave jar file
      - name: download Jenkins Slave jar
        get_url:
          url: "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/{{ slave_jar_version }}/remoting-{{ slave_jar_version }}.jar"
          dest: /home/jenkins/slave.jar
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave
          - jenkins_slave.download_slave_jar

      # copy the script file to start the jenkins slave
      - name: copy Jenkins Slave files
        synchronize:
          src: ../ci-slave-local/start-slave.sh
          dest: /home/jenkins/start-slave.sh
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave
          - jenkins_slave.copy_files

      # in case any docker container is running, stop them
      - name: stop all running docker container
        shell: docker stop $(docker ps -a -q)
        become: yes
        become_user: sapmachine
        failed_when: false
        tags:
          - docker.container_stop

      # enable Docker IPv6
      - name: install Docker Daemon configuration
        copy:
          src: daemon.json
          dest: /etc/docker/daemon.json
          owner: root
          group: root
          mode: 0644
        become: yes
        tags:
          - docker.config_install

      - name: reload the Docker Daemon configuration
        systemd: state=restarted name=docker
        become: yes
        tags:
          - docker.config_reload

      # stop all running java processes (jenkins slave)
      - name: stop all Java processes
        command: killall -9 java
        become: yes
        failed_when: false
        tags:
          - jenkins_slave
          - java.kill_all

      # update docker images
      - name: remove all docker container
        shell: docker rm $(docker ps -a -q)
        become: yes
        become_user: sapmachine
        failed_when: false
        tags:
          - docker.container_remove

      - name: purge dangling docker images
        command: docker images purge
        become: yes
        become_user: sapmachine
        tags:
          - docker.images_purge

      - name: remove all docker images
        shell: docker rmi $(docker images -a -q)
        become: yes
        become_user: sapmachine
        failed_when: false
        tags:
          - docker.images_remove

      # start all docker container
      - name: run docker-compose
        command: docker-compose -f ./compose.yml up -d --build
        args:
          chdir: /home/sapmachine/sapmachine_master
        become: yes
        become_user: sapmachine
        tags:
          - docker.compose

      # these files are no longer needed and contain sensitive data
      # remove them
      - name: remove sapmachine_master
        file:
          path: /home/sapmachine/sapmachine_master
          state: absent
        become: yes
        become_user: sapmachine
        tags:
          - sapmachine_master.remove

      # wait for the jenkins master server to come up
      # and read the SapMachine user password
      - name: wait for Jenkins Master to come up
        command: docker exec ci bash /usr/share/jenkins/read-sapmachine-pw.sh
        become: yes
        become_user: sapmachine
        register: sapmachine_pw
        tags:
          - jenkins_master.wait_for

      # read the jenkins slave secret for the jenkins slave
      - name: read Jenkins Slave secret
        command: "docker exec ci bash /usr/share/jenkins/read-slave-secret.sh {{ jenkins_slave_name }}"
        become: yes
        become_user: jenkins
        register: slave_secret
        tags:
          - jenkins_slave
          - jenkins_slave.secret

      # start the jenkins slave
      - name: start Jenkins Slave
        command: "/home/jenkins/start-slave.sh {{ jenkins_master_url }} {{ slave_secret.stdout }}"
        args:
          chdir: /home/jenkins
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave
          - jenkins_slave.start

      # start the cAdvisor Docker container
      # see: https://github.com/google/cadvisor
      - name: start cAdvisor Docker container
        docker_container:
          name: cadvisor
          image: google/cadvisor:latest
          restart_policy: unless-stopped
          volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
          ports:
            - 8080:8080
          detach: yes
        become: yes
        tags:
          docker.start_cAdvisor

      # display the jenkins SapMachine password
      - name: show Jenkins SapMachine password
        debug:
          msg:
            - "user: SapMachine"
            - "password: {{ sapmachine_pw.stdout }}"
