# used for creating the new CPU Release Build in January/April/July/October.
# new feature releases updates in March and Septemberb are done via publish-gardenlinux-imagesONCE-DoNotUse.yml
name: Build and Publish SapMachine new CPU Releases container images to the SAP GitHub Container Registry
on:
  workflow_dispatch:

jobs:
  publish_images:
    strategy:
        matrix:
          sapMachineVersion: [17, 21, 25]
          gardenLinuxVersion: [1592.15]
    uses: ./.github/workflows/publish-container-images.yml
    with:
      sapMachineVersion: ${{ matrix.sapMachineVersion }}
      gardenLinuxVersion:  ${{ matrix.gardenLinuxVersion }}
